# Generated by Django 4.0.4 on 2022-05-26 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtubeapp', '0003_alter_post_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
