# Generated by Django 4.0.4 on 2022-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtubeapp', '0004_alter_post_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(upload_to='ads/')),
            ],
        ),
    ]
