# Generated by Django 4.0.4 on 2022-05-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtubeapp', '0005_ads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='thumbnail',
            new_name='ad',
        ),
    ]
