# Generated by Django 4.0.4 on 2022-06-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtubeapp', '0014_category_post_category_post_likes_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploader',
            field=models.IntegerField(default=1, verbose_name='Video Uploader'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
