# Generated by Django 4.0.4 on 2022-06-01 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newtubeapp', '0015_alter_post_uploader_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploader',
        ),
        migrations.AddField(
            model_name='post',
            name='uploader',
            field=models.ManyToManyField(related_name='uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
