# Generated by Django 4.0.4 on 2022-06-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtubeapp', '0016_remove_post_uploader_post_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploader',
        ),
        migrations.AddField(
            model_name='post',
            name='uploader',
            field=models.IntegerField(default=1, verbose_name='Video Uploader'),
        ),
    ]
