# Generated by Django 4.0.4 on 2022-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtubeapp', '0017_remove_post_uploader_post_uploader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='post',
            name='uploader',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
