# Generated by Django 4.0.4 on 2022-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtubeapp', '0018_delete_category_alter_post_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(default='#NewTube', max_length=255),
        ),
    ]
