# Generated by Django 4.0.4 on 2022-06-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtubeapp', '0020_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_dp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_dps/'),
        ),
    ]
