# Generated by Django 4.0.4 on 2022-06-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtubeapp', '0022_post_dislikes_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
