# Generated by Django 4.0.4 on 2022-06-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtubers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
